title: Aakanksha Tiwari
email: taakanksha5@gmail.com
description: >- 
  Personal website showcasing projects, blogs, and publications.
baseurl: ""
url: "https://aakankshatiwari.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
